### PR TITLE
Improve boot scripts to give users run-control

### PR DESCRIPTION
**Pull request by steve-gregory**
Options are:
- Run on boot
- Run on each deployment

## Highlight Reel
- Include new 'strategy' field in serializer for BootScript.
- Include 'created_by' by using request's current user
- Remove bad validation (See 56fa1763afd8ecee33ff5953639b5e6583abd97e)

(Rebirth of https://github.com/cyverse/atmosphere/pull/404)

## Checklist before merging Pull Requests
- [x] Reviewed and approved by at least one other contributor.
- [x] [Reviewed and approved atmosphere-ansible companion PR](https://github.com/cyverse/atmosphere-ansible/pull/104)

### CODE REVIEW

**Comment by cdosborn** [comment]
landsacpe is busted, widget says new errors, but on their site it says none :/

**Comment by julianpistorius** [comment]
Thanks @cdosborn. I'll figure it out.

**Comment by steve-gregory** [comment]
To be updated after Review 1:
- Allow users option to 'fire and forget' boot script or 'wait for' boot script
   - Wait for boot scripts will be subject to an ## second/minute timeout.
- Allow users option to 'email notify' (Only available if they choose the 'wait for' boot script type)
- Update atmosphere-ansible to select the appropriate option based on the users choice.

**Comment by steve-gregory** [comment]
:shipit:

**Pull request merged**
