### PR TITLE
Add a new instance action: Resize

### PR DESCRIPTION
**Pull request by xuhang57**
## Description

API change for allowing a new instance action: Resize. 

## Checklist before merging Pull Requests
- [x] Polling instance more often so the user doesn't have to refresh to see the size change
- [ ] Unit test for testing this new action 
- [ ] Reviewed and approved by at least one other contributor.

## Related PRs
Troposphere - https://github.com/cyverse/troposphere/pull/558

## Potential Problem

We may don't want to allow any user to resize from a larger flavor to a smaller one. OpenStack Horizon allows the user to do that and it might cause problems. 
Will discuss this in more details. 

Thanks
Lucas

### CODE REVIEW

**Comment by steve-gregory** [comment]
Hi @xuhang57 great progress on this! I've made a 'suggestions PR' that will fix some of your problems and take this a bit further: https://github.com/xuhang57/atmosphere/pull/2

**Comment by xuhang57** [comment]
@steve-gregory  Nice. thanks for the refactor and review. Next step is to add new tests for it. I hope I can get this done by this week. Examining some bugs in our atmosphere server currently.

**Comment by xuhang57** [comment]
Just want to confirm that I should write the unit test with using the django test framework, correct?

**Comment by steve-gregory** [comment]
@xuhang57 yes you can use any of the files in the directory `https://github.com/cyverse/atmosphere/tree/master/api/tests/v2` as an example

**Comment by xuhang57** [comment]
@steve-gregory Thanks, Steve! I will do it as soon as possible.

**Comment by xuhang57** [comment]
@steve-gregory Blocked on writing the unit test for this. Hopefully, I can get this done soon.

**Comment by xuhang57** [comment]
update, depends on https://github.com/cyverse/atmosphere/pull/307

**Comment by steve-gregory** [comment]
@xuhang57 I will remove the `wip` tag when you make the changes post-merge of #307

**Comment by xuhang57** [comment]
Added the new test and ready for review 👍 @steve-gregory

**Comment by steve-gregory** [comment]
Failing test cases must be addressed prior to merging.

**Comment by xuhang57** [comment]
Cannot believe it's been 10 days since the last comment. Will start working this next Monday.

**Comment by xuhang57** [comment]
hope I can finish this within this year. sorry for the delay

**Comment by xuhang57** [comment]
Do we have any plan for this? Thanks!

**Comment by steve-gregory** [comment]
@xuhang57 if you can get the test cases fixed and address the merge conflict, we can move forward with this PR.

**Comment by xuhang57** [comment]
Will reopen it once it is rebased with the master branch

**Pull request closed without merging**
