### PR TITLE
Problem: Instances fail to launch on Havana due to API change

### PR DESCRIPTION
**Pull request by julianpistorius**
Solution: Don't assume port has a project_id, and use a default.

## Checklist before merging Pull Requests
- ~[ ] New test(s) included to reproduce the bug/verify the feature~
- ~[ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature~
- [x] Reviewed and approved by at least one other contributor.
- ~[ ] If necessary, include a snippet in CHANGELOG.md~

### CODE REVIEW

**Comment by lenards** [comment]
Looks good.

**Comment by lenards** [comment]
I'm 👍

**Comment by githubdavidchoi** [comment]
p {margin-top:0px;margin-bottom:0px;} 


	
	
I'm sorry. 
I do not subscribe this any more. But I do not know how to cancel my subscription. Can you tell me the way? Thank you.
Daum 메일앱에서 보냈습니다.


--------- 원본 메일 ---------
보낸사람: Andrew Lenards <notifications@github.com>
받는사람: cyverse/atmosphere <atmosphere@noreply.github.com>
참조: Subscribed <subscribed@noreply.github.com>
날짜: Sat Jul 15 01:19:28 GMT+09:00 2017
제목: Re: [cyverse/atmosphere] Problem: Instances fail to launch on Havana due to API change (#419)



	I'm 👍

**Comment by lenards** [comment]
Yes, I can tell you "the way". 

The Tao is mysterious. But the reason you get these messages is not. It is because you clicked on "watch" for the Atmosphere GitHub repository. 

The steps are:
- go to https://github.com/cyverse/atmosphere/watchers
- click on "Unwatch" in the upper right corner

Example:
unwatch-example

**Comment by githubdavidchoi** [comment]
p {margin-top:0px;margin-bottom:0px;} 


	
	
Thank you. It's very simple. Have a nice day.
Daum 메일앱에서 보냈습니다.


--------- 원본 메일 ---------
보낸사람: Andrew Lenards <notifications@github.com>
받는사람: cyverse/atmosphere <atmosphere@noreply.github.com>
참조: githubdavidchoi <ks-hai@hanmail.net>,Mention <mention@noreply.github.com>
날짜: Tue Jul 18 00:55:46 GMT+09:00 2017
제목: Re: [cyverse/atmosphere] Problem: Instances fail to launch on Havana due to API change (#419)



	@githubdavidchoi - Yes, I can tell you "the way".
The Tao is mysterious. But the reason you get these messages is not. It is because you clicked on "watch" for the Atmosphere GitHub repository.
The steps are:

go to https://github.com/cyverse/atmosphere/watchers
click on "Unwatch" in the upper right corner

Example:

**Comment by lenards** [comment]
You are very welcome David - thank you for your interest in Atmosphere.

**Pull request merged**
