### PR TITLE
Deploy by default

### PR DESCRIPTION
**Pull request by cdosborn**
## Description
@julianpistorius 

## Checklist before merging Pull Requests
- [ ] New test(s) included to reproduce the bug/verify the feature
- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature
- [x] Reviewed and approved by at least one other contributor.
- [ ] If necessary, include a snippet in CHANGELOG.md
- [ ] New variables supported in Clank
- [ ] New variables committed to secrets repos

### CODE REVIEW

**Comment by julianpistorius** [comment]
Looks good. @lenards please merge.

**Comment by lenards** [comment]
📦

**Comment by lenards** [comment]
This work will ensure that a _created_ instance will be in "deploy", correct?

**Comment by cdosborn** [comment]
rip, i meant to add a description sorry @lenards

**Comment by lenards** [comment]
No worries Connor!

**Pull request merged**
