### PR TITLE
Add Guacamole SSH color selection to settings page

### PR DESCRIPTION
**Pull request by calvinmclean**
## Description

This PR would allow users to choose the color of their Guacamole SSH session.

[Troposphere PR #688](https://github.com/cyverse/troposphere/pull/688)

## Next steps:
- [x] **Need to get the color setting into the web_token view so Guacamole knows which is picked**
- [x] Pass Travis build and do some more testing
- [x] Add `guacamole_color` column to production database

## Checklist before merging Pull Requests
- [x] Reviewed and approved by at least one other contributor.
- [ ] If necessary, include a snippet in CHANGELOG.md

### CODE REVIEW

**Comment by steve-gregory** [comment]
ToDo: Re-order migrations

**Comment by calvinmclean** [comment]
✅  Reordered migrations

**Comment by calvinmclean** [comment]
This last commit changes the default color to white on black. Guacamole's default is `gray-black`. I set the default in the database migration rather than changing Troposphere code because if Atmosphere passes `default` to the Guacamole connection, it will show `gray-black` instead of `white-black`.

**Comment by steve-gregory** [comment]
:shipit: for `v29`. Thanks @calvinmclean !

**Pull request merged**
