### PR TITLE
Introduce linting 💅

### PR DESCRIPTION
**Pull request by cdosborn**
## Description

Introducing linting into a project can be tricky. This script runs a strict variant on newly added files, and a lenient variant on modified files. This is a win for two reasons:
- New code will be  💅 
- Old code will gradually become 💅 

The linting tool is [prospector](https://prospector.landscape.io/en/master/). It has a lot of common sense defaults, and bundles pyflakes/pylint and others. It supports vulture as a plugin so we can nuke all our dead code.

## Checklist before merging Pull Requests
- [ ] New test(s) included to reproduce the bug/verify the feature
- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature
- [ ] Reviewed and approved by at least one other contributor.
- [ ] If necessary, include a snippet in CHANGELOG.md
- [ ] New variables supported in Clank
- [ ] New variables committed to secrets repos

### CODE REVIEW

**Comment by cdosborn** [comment]
note to self: make this robust against non-existent sha's

**Comment by xuhang57** [comment]
This is really neat 👍 

```
Check Information
=================
         Started: 2017-08-04 13:43:28.998086
        Finished: 2017-08-04 13:46:50.653449
      Time Taken: 201.66 seconds
       Formatter: grouped
        Profiles: default, no_doc_warnings, no_test_warnings, strictness_medium, strictness_high, strictness_veryhigh, no_member_warnings
      Strictness: None
  Libraries Used: flask, celery, django
       Tools Run: dodgy, mccabe, pep8, profile-validator, pyflakes, pylint
  Messages Found: 3317
```
So it runs 6 tools together with one command.

**Comment by cdosborn** [comment]
I tacked on two commits, to make the generate requirements script more robust. 

@steve-gregory, I was bumping up against a lot of issues even with the least strict version of the linter. I think this will be a large improvement, but it comes with a caveat. Atmo developers need to be willing to clean up files they just touch or fix bugs in (or revise the rules that are applied via the linter). Next pr will get a more lenient set of rules, that we run over all files.

**Comment by steve-gregory** [comment]
:shipit:

**Pull request merged**
