### PR TITLE
(with @calvinmclean) Guacamole Integration (web_token)

### PR DESCRIPTION
**Pull request by steve-gregory**
... from views/guacamole (in troposphere) to the web_tokens API as
created for web desktop.

## Related to:
- https://github.com/cyverse/troposphere/pull/639
- https://github.com/cyverse/atmosphere-ansible/pull/78
- https://github.com/cyverse/clank/pull/167/

## Description

Please describe your pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue. When linking to an issue, please use `refs #...` in the description of the pull request.

## Checklist before merging Pull Requests
- [ ] New test(s) included to reproduce the bug/verify the feature
- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature
- [ ] Reviewed and approved by at least one other contributor.
- [ ] If necessary, include a snippet in CHANGELOG.md

### CODE REVIEW

**Comment by steve-gregory** [comment]
FYI -- No new test have been added, behave test case failure not related to this PR 👍

**Comment by cdosborn** [comment]
Here are some changes I propose:
https://github.com/steve-gregory/atmosphere/pull/10

**Comment by c-mart** [comment]
@sgregory from https://wiki.cyverse.org/wiki/pages/viewpage.action?pageId=33325764&focusedCommentId=34046409#comment-34046409

> Atmosphere API would be responsible for setting new Openstack Security Group default rules: TCP to 5905 ALLOW FROM guacamole server both directions

Is that for a separate PR?

**Comment by steve-gregory** [comment]
@c-mart that change should be done, for each provider, in `provider.cloud_config['network']['default_security_rules']`. 

The `DEFAULT_RULES` variable in `atmosphere/settings/__init__.py` is deprecated.

**Pull request merged**
