### PR TITLE
Fix check req w versioned pip tools

### PR DESCRIPTION
**Pull request by cdosborn**
## Description

**Problem:** travis and local disagree on requirements
**Solution:** agree upon a version of pip-tools

This fix also regenerates the requirements to pass travis.

## Checklist before merging Pull Requests
- [ ] New test(s) included to reproduce the bug/verify the feature
- [ ] Documentation created/updated at [Example link to documentation](https://example.test/doc#new_section) to give context to the feature
- [ ] Reviewed and approved by at least one other contributor.
- [ ] If necessary, include a snippet in CHANGELOG.md
- [ ] New variables supported in Clank
- [ ] New variables committed to secrets repos

### CODE REVIEW

**Comment by cdosborn** [comment]
@steve-gregory this is goofing up because the linter, but i verified that it works on mickey

**Comment by cdosborn** [comment]
This pr fixes the linter issue https://github.com/cyverse/atmosphere/pull/472

**Comment by lenards** [comment]
Re-running the Travis build for this.

**Comment by cdosborn** [comment]
Conflicts have been addressed.

**Comment by steve-gregory** [comment]
@cdosborn looks like travis is still failing on the requirements check -- Let me know if we should :shipit:  now or wait for a fix within this PR before we :shipit:

**Comment by cdosborn** [comment]
Addressed!

**Pull request merged**
